services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    restart: unless-stopped

  game-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8083:8081"
    environment:
      - PORT=8081
    restart: unless-stopped
